### ISSUE TITLE
registros en JSON desde 2005-07-18 no tienen `time_start`

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/registro_visitas_TC#2]
creo que voy a iniciar un chequeo manual para evitar que se nos pase info cc @goddamnhippie

**Comment by aniversarioperu** [comment]
estoy poniendo los registros curados en este archivo https://github.com/aniversarioperu/registro_visitas_TC/blob/master/curated_records.json
- sin trailing spaces
- sin doble whitspaces
- numero de DNI que no tengan menos de 8 caracters (si faltan le pongo numero 0 adelante)
- datos normalizados usando OpenRefine:
  - ej. "DR. Ricardo" y "Dr   Ricardo" son lo mismo, y son reemplados por "Dr. Ricardo"

**Comment by beathyate** [comment]
Si, esta era una primera pasada, me imagino que faltará poner headers, etc, hoy no creo que pueda avanzar mucho pero lo reviso en la semana.

**Comment by aniversarioperu** [comment]
qué chevere tu script, funciona muy bien!

**Comment by beathyate** [comment]
Gracias, eventualmente me gustaría migrarlo a algo que permita usar código para cada campo, para así poder manejar casos especiales, porque el markup varía un montón. El fin le voy a dar una revisada.
